# 시도/삶의만족도/건강/안전/환경/경제/교육/관계및사회참여/여가 컬럼으로

In [118]:
%pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sunky\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sunky\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [119]:
import pandas as pd

In [120]:
happy_life=pd.read_excel('happy\대한민국행복지도_삶의만족도.xlsx',engine='openpyxl')
happy_life.head()

   No     시도   구군  삶의 만족도
0   1  서울특별시  종로구  0.4437
1   2  서울특별시   중구  0.4976
2   3  서울특별시  용산구  0.6161
3   4  서울특별시  성동구  0.4729
4   5  서울특별시  광진구  0.4041

In [121]:
happy_merge=happy_life.groupby('시도')[['삶의 만족도']].mean()
happy_merge.head() # 이 옆의 여가... 주루룩 나오도록

         삶의 만족도
시도
강원도    0.619506
경기도    0.426023
경상남도   0.530794
경상북도   0.502223
광주광역시  0.484480

In [122]:
happy_health=pd.read_excel('happy\대한민국행복지도_건강.xlsx',engine='openpyxl')
happy_health.head()

,No,시도,구군,평균,주관적 건강수준 인지율,인구 십만명당 정신건강증진기관 수,인구 천명당 의료기관 종사 의사수,건강생활실천율,인구 천명당 의료기관병상수
0,1,서울특별시,종로구,0.9220,0.8424,0.6914,1.0000,0.9697,0.7616
1,2,서울특별시,중구,0.6742,0.5772,0.4106,0.9995,0.9669,0.4043
2,3,서울특별시,용산구,0.5898,0.9819,0.3353,0.6046,0.9844,0.1433
3,4,서울특별시,성동구,0.4794,0.5465,0.3321,0.5783,0.9776,0.2111
4,5,서울특별시,광진구,0.6373,0.8534,0.7393,0.6352,0.8022,0.1936

In [123]:
happy_safe=pd.read_excel('happy\대한민국행복지도_안전.xlsx',engine='openpyxl')
happy_safe.head()

,No,시도,구군,평균,사회안전에 대한 인식 b),인구 천명당 cctv 대수 b),인구 십만명당 응급의료기관 및 응급실 운영기관수,단위면적당 지역경찰관서 수,지역안전등급 현황 중 '교통사고 및 화재' a)
0,1,서울특별시,종로구,0.7470,0.9965,0.4796,0.7498,0.9998,0.0162
1,2,서울특별시,중구,0.9320,0.9707,0.8214,0.6938,1.0000,0.3014
2,3,서울특별시,용산구,0.5537,0.6641,0.4311,0.1768,0.8923,0.5075
3,4,서울특별시,성동구,0.5347,0.7452,0.4330,0.1562,0.9800,0.3014
4,5,서울특별시,광진구,0.6072,0.7179,0.2196,0.2019,0.9785,0.7117

In [124]:
happy_environ=pd.read_excel('happy\대한민국행복지도_환경.xlsx',engine='openpyxl')
happy_environ.head()

,No,시도,구군,평균,환경체감도 b),인구 천명당 1일 산업폐수 방류량 a),도시지역 중 '녹지지역 비율',미세먼지(PM2.5) a) b),주민 1인당 생활폐기물배출량 a)
0,1,서울특별시,종로구,0.4637,0.4658,0.7223,0.2012,0.7704,0.0006
1,2,서울특별시,중구,0.2865,0.1077,0.6957,0.0013,0.6617,0.0000
2,3,서울특별시,용산구,0.5030,0.3142,0.7185,0.1349,0.6895,0.4571
3,4,서울특별시,성동구,0.4196,0.1480,0.6868,0.0347,0.3757,0.7426
4,5,서울특별시,광진구,0.4992,0.1229,0.6940,0.0574,0.7235,0.7016

In [125]:
happy_econo=pd.read_excel('happy\대한민국행복지도_경제.xlsx',engine='openpyxl')
happy_econo.head()

,No,시도,구군,평균,1인당 지역내총생산(GRDP),인구 천명당 사업체수,인구 천명당 종사자수,국민기초생활보장 수급자비율 a),종사자 천명당 영세자영업자 수 a)
0,1,서울특별시,종로구,1.0000,1.0000,1.0000,1.0000,0.7564,0.9037
1,2,서울특별시,중구,0.9806,1.0000,1.0000,1.0000,0.6718,0.9177
2,3,서울특별시,용산구,0.6915,0.6334,0.5493,0.7282,0.7910,0.8341
3,4,서울특별시,성동구,0.6533,0.5132,0.5368,0.6849,0.8243,0.8377
4,5,서울특별시,광진구,0.4445,0.2906,0.3424,0.3870,0.8681,0.7480

In [126]:
happy_edu=pd.read_excel('happy\대한민국행복지도_교육.xlsx',engine='openpyxl')
happy_edu.head()

,No,시도,구군,평균,교원 1인당 학생수,영유아 천명당 보육시설 수,인구 십만명당 학교수,인구 천명당 사설학원수
0,1,서울특별시,종로구,0.6839,0.8505,0.6248,0.2249,0.8126
1,2,서울특별시,중구,0.5013,0.8729,0.4147,0.2294,0.2944
2,3,서울특별시,용산구,0.2679,0.6479,0.3804,0.1281,0.1629
3,4,서울특별시,성동구,0.2464,0.7661,0.2270,0.1308,0.3366
4,5,서울특별시,광진구,0.4879,0.9309,0.4263,0.1278,0.4607

In [127]:
happy_relation=pd.read_excel('happy\대한민국행복지도_관계및사회참여.xlsx',engine='openpyxl')
happy_relation.head()

,No,시도,구군,평균,인구 십만명당 자살률 a),1인가구(독거노인 제외) 비율 a),독거노인가구 비율 a),인구 십만명당 사회적기업수,가족관계 만족도 b)
0,1,서울특별시,종로구,0.7425,0.8318,0.0057,0.7593,0.9981,0.5949
1,2,서울특별시,중구,0.4608,0.5462,0.0107,0.7254,1.0000,0.2329
2,3,서울특별시,용산구,0.4317,0.7288,0.0211,0.7754,0.7194,0.2009
3,4,서울특별시,성동구,0.4182,0.7288,0.0791,0.8332,0.6783,0.0937
4,5,서울특별시,광진구,0.3519,0.9434,0.0051,0.8541,0.2461,0.2058

In [128]:
happy_leisure=pd.read_excel('happy\대한민국행복지도_관계및사회참여.xlsx',engine='openpyxl')
happy_leisure.head()

,No,시도,구군,평균,인구 십만명당 자살률 a),1인가구(독거노인 제외) 비율 a),독거노인가구 비율 a),인구 십만명당 사회적기업수,가족관계 만족도 b)
0,1,서울특별시,종로구,0.7425,0.8318,0.0057,0.7593,0.9981,0.5949
1,2,서울특별시,중구,0.4608,0.5462,0.0107,0.7254,1.0000,0.2329
2,3,서울특별시,용산구,0.4317,0.7288,0.0211,0.7754,0.7194,0.2009
3,4,서울특별시,성동구,0.4182,0.7288,0.0791,0.8332,0.6783,0.0937
4,5,서울특별시,광진구,0.3519,0.9434,0.0051,0.8541,0.2461,0.2058

In [140]:
import os
path='happy/'
file_list=os.listdir(path)
file_list

['대한민국행복지도_건강.xlsx',
 '대한민국행복지도_경제.xlsx',
 '대한민국행복지도_관계및사회참여.xlsx',
 '대한민국행복지도_교육.xlsx',
 '대한민국행복지도_삶의만족도.xlsx',
 '대한민국행복지도_안전.xlsx',
 '대한민국행복지도_여가.xlsx',
 '대한민국행복지도_환경.xlsx']

In [130]:
keywords={'건강':'happy_health','안전':'happy_safe','환경':'happy_environ','경제':'happy_econo','교육':'happy_edu',
          '관계및사회참여':'happy_relation','여가':'happy_leisure'
}

try:
    for i in file_list:
        if i.endswith('.xlsx'):
            for x,y in keywords.items():
                if x in i:
                    keywords[x]=pd.read_excel(path+i,engine='openpyxl')
                    health=keywords[x].groupby('시도')[['평균']].mean()
                    happy_merge=pd.merge(happy_merge,health.rename(columns={'평균':x}),on='시도')
except:
    print(i)

In [131]:
# 미션: 어느 특정 시를 누르면 그 시만 가져와서 구군별 분석
happy_merge.head()

,삶의 만족도,건강,경제,관계및사회참여,교육,안전,여가,환경
시도,,,,,,,,
강원도,0.619506,0.329506,0.386861,0.563122,0.488533,0.548000,0.632750,0.639839
경기도,0.426023,0.353952,0.468926,0.601532,0.668619,0.325255,0.377561,0.557977
경상남도,0.530794,0.312722,0.325017,0.395378,0.624022,0.475561,0.463750,0.735600
경상북도,0.502223,0.264114,0.303355,0.402183,0.428252,0.484835,0.490804,0.614265
광주광역시,0.484480,0.632300,0.387380,0.637800,0.689680,0.266440,0.454980,0.607480

In [132]:
happy_leisure['구군']

0       종로구
1        중구
2       용산구
3       성동구
4       광진구
       ...
224     함양군
225     거창군
226     합천군
227     제주시
228    서귀포시
Name: 구군, Length: 229, dtype: object

In [133]:
keywords={'건강':'happy_health','안전':'happy_safe','환경':'happy_environ','경제':'happy_econo','교육':'happy_edu',
          '관계및사회참여':'happy_relation','여가':'happy_leisure'}
for x,y in keywords.items():
    print(x)
    print(y)

건강
happy_health
안전
happy_safe
환경
happy_environ
경제
happy_econo
교육
happy_edu
관계및사회참여
happy_relation
여가
happy_leisure

In [134]:
happy_leisure['시도']=='서울특별시'

0       True
1       True
2       True
3       True
4       True
       ...
224    False
225    False
226    False
227    False
228    False
Name: 시도, Length: 229, dtype: bool

In [135]:
province='서울특별시'
happy_leisure[happy_leisure['시도']==province]

,No,시도,구군,평균,인구 십만명당 자살률 a),1인가구(독거노인 제외) 비율 a),독거노인가구 비율 a),인구 십만명당 사회적기업수,가족관계 만족도 b)
0,1,서울특별시,종로구,0.7425,0.8318,0.0057,0.7593,0.9981,0.5949
1,2,서울특별시,중구,0.4608,0.5462,0.0107,0.7254,1.0000,0.2329
2,3,서울특별시,용산구,0.4317,0.7288,0.0211,0.7754,0.7194,0.2009
3,4,서울특별시,성동구,0.4182,0.7288,0.0791,0.8332,0.6783,0.0937
4,5,서울특별시,광진구,0.3519,0.9434,0.0051,0.8541,0.2461,0.2058
5,6,서울특별시,동대문구,0.1339,0.6459,0.0155,0.7647,0.1916,0.1147
6,7,서울특별시,중랑구,0.2511,0.6059,0.2462,0.7538,0.2771,0.1301
7,8,서울특별시,성북구,0.3539,0.7516,0.1311,0.8007,0.3912,0.1845
8,9,서울특별시,강북구,0.0893,0.4295,0.2800,0.6578,0.1834,0.0747
9,10,서울특별시,도봉구,0.5292,0.8072,0.7646,0.7370,0.2784,0.0920
10,11,서울특별시,노원구,0.4966,0.8167,0.7178,0.7254,0.1809,0.1601
11,12,서울특별시,은평구,0.5292,0.6459,0.5152,0.7754,0.6847,0.0579
12,13,서울특별시,서대문구,0.2809,0.7210,0.0426,0.7908,0.3562,0.1739
13,14,서울특별시,마포구,0.4891,0.7769,0.0107,0.8501,0.7373,0.2081
14,15,서울특별시,양천구,0.6415,0.8748,0.8489,0.8243,0.2008,0.1992
15,16,서울특별시,강서구,0.2570,0.7804,0.1696,0.8151,0.2023,0.0597
16,17,서울특별시,구로구,0.4795,0.7663,0.3458,0.8151,0.4231,0.2099
17,18,서울특별시,금천구,0.3858,0.5693,0.0390,0.7647,0.8496,0.1131
18,19,서울특별시,영등포구,0.4053,0.6459,0.0282,0.8104,0.7881,0.1097
19,20,서울특별시,동작구,0.2240,0.7804,0.0269,0.8375,0.2085,0.0949
20,21,서울특별시,관악구,0.1551,0.5601,0.0000,0.8501,0.2591,0.1137
21,22,서울특별시,서초구,0.4501,0.9169,0.3382,0.8905,0.2427,0.1014
22,23,서울특별시,강남구,0.3016,0.8039,0.1103,0.8732,0.2844,0.0619
23,24,서울특별시,송파구,0.4959,0.8724,0.3927,0.8804,0.2274,0.2266
24,25,서울특별시,강동구,0.4123,0.7479,0.4657,0.8287,0.1829,0.1738

In [179]:
happy_merge2=happy_life.groupby(['시도','구군'],as_index=False)[['삶의 만족도']].mean()

keywords={'건강':'happy_health','안전':'happy_safe','환경':'happy_environ','경제':'happy_econo','교육':'happy_edu',
          '관계및사회참여':'happy_relation','여가':'happy_leisure'
}
try:
    for i in file_list:
        if i.endswith('.xlsx'):
            for x in keywords.keys():
                if x in i:
                    keywords[x]=pd.read_excel(path+i,engine='openpyxl')
                    temp=keywords[x].groupby(['시도','구군'],as_index=False)[['평균']].mean()
                    happy_merge2=pd.merge(happy_merge2,temp.rename(columns={'평균':x}))
except:
    print(i)

province_list=list(happy_merge2['시도'])
available=[]
for entry in province_list:
    if entry not in available:
        available.append(entry)
print(f'다음은 조회 가능한 시/도입니다.\n{available}')
print('위 시/도 중 하나를 그대로 입력하지 않으면 오류가 뜨니 주의하시기 바랍니다.')
province=input('조회하고자 하는 시/도를 입력하세요.')
happy_merge2[happy_merge2['시도']==province]

다음은 조회 가능한 시/도입니다.
['강원도', '경기도', '경상남도', '경상북도', '광주광역시', '대구광역시', '대전광역시', '부산광역시', '서울특별시', '세종특별자치시', '울산광역시', '인천광역시', '전라남도', '전라북도', '제주특별자치도', '충청남도', '충청북도']
위 시/도 중 하나를 그대로 입력하지 않으면 오류가 뜨니 주의하시기 바랍니다.

     시도    구군  삶의 만족도      건강      경제  관계및사회참여      교육      안전      여가      환경
18  경기도   가평군  0.0473  0.6021  0.3195   0.2763  0.4350  0.4336  0.6209  0.8264
19  경기도   고양시  0.4211  0.3542  0.4146   0.7029  0.7661  0.2593  0.2897  0.6464
20  경기도   과천시  0.9464  0.4950  0.6877   0.9200  0.7262  0.5269  0.5638  0.7482
21  경기도   광명시  0.5261  0.3612  0.3779   0.9014  0.7989  0.4316  0.2223  0.6023
22  경기도   광주시  0.2806  0.3259  0.5155   0.6939  0.3887  0.1970  0.2677  0.6372
23  경기도   구리시  0.3452  0.5670  0.4192   0.6446  0.6839  0.4206  0.2520  0.5781
24  경기도   군포시  0.7367  0.3599  0.4690   0.9343  0.8557  0.4638  0.3326  0.6277
25  경기도   김포시  0.4879  0.2079  0.5090   0.6917  0.6643  0.2981  0.2691  0.6119
26  경기도  남양주시  0.3529  0.1406  0.3032   0.8731  0.6473  0.2716  0.3090  0.7385
27  경기도  동두천시  0.0158  0.7414  0.2125   0.4181  0.4777  0.2929  0.2116  0.5047
28  경기도   부천시  0.2592  0.5367  0.4546   0.7119  0.5391  0.4468  0.1534  0.3525
29  경기도   성남시  0.7403  0.5489  0.5456   0.5492  0.7748  0.3541  0.3240  0.6296
30  경기도   수원시  0.5090  0.3975  0.4787   0.6117  0.7801  0.4344  0.3505  0.4935
31  경기도   시흥시  0.2386  0.2895  0.6114   0.4479  0.6935  0.3102  0.4324  0.3514
32  경기도   안산시  0.1039  0.2814  0.5510   0.3177  0.6281  0.4194  0.2747  0.4483
33  경기도   안성시  0.1230  0.1904  0.5597   0.4324  0.8854  0.0707  0.5242  0.4621
34  경기도   안양시  0.6081  0.4105  0.5658   0.7167  0.8866  0.4114  0.3354  0.5422
35  경기도   양주시  0.1382  0.2252  0.4818   0.7096  0.7058  0.2128  0.5063  0.2943
36  경기도   양평군  0.8345  0.2278  0.2334   0.4959  0.2166  0.3619  0.6428  0.9072
37  경기도   여주시  0.2904  0.3271  0.3567   0.3756  0.7788  0.2874  0.5813  0.5744
38  경기도   연천군  0.7871  0.3187  0.1592   0.2145  0.4499  0.3704  0.7067  0.7912
39  경기도   오산시  0.1828  0.2476  0.4448   0.5680  0.7400  0.4564  0.3735  0.4327
40  경기도   용인시  0.7721  0.2603  0.4828   0.8206  0.8399  0.3990  0.2485  0.6420
41  경기도   의왕시  0.6721  0.3316  0.4296   0.8661  0.8337  0.4408  0.3558  0.6481
42  경기도  의정부시  0.1031  0.5362  0.3016   0.5723  0.8666  0.3894  0.2050  0.6434
43  경기도   이천시  0.6505  0.3160  0.6725   0.5314  0.5669  0.2407  0.4178  0.2897
44  경기도   파주시  0.3401  0.3232  0.5031   0.8055  0.5562  0.1751  0.4660  0.4036
45  경기도   평택시  0.1617  0.1359  0.6050   0.3863  0.6550  0.2515  0.2951  0.2450
46  경기도   포천시  0.1591  0.3160  0.6260   0.2324  0.7527  0.1127  0.5181  0.4173
47  경기도   하남시  0.7569  0.2210  0.4264   0.5394  0.4260  0.1968  0.2935  0.7839
48  경기도   화성시  0.6160  0.3758  0.8189   0.6861  0.7077  0.1456  0.3607  0.4235