In [5]:
%pip install html5lib

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: html5lib in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from html5lib) (0.5.1)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [6]:
# 환율 표만 나오게끔

from bs4 import BeautifulSoup
import requests
import pandas as pd

url='https://finance.naver.com/marketindex/exchangeList.naver'

dfs=pd.read_html(url, encoding='cp949',header=1)
dfs

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

[              통화명    매매기준율     사실 때     파실 때    보내실 때    받으실 때  미화환산율
 0          미국 USD  1454.90  1480.36  1429.44  1469.10  1440.70  1.000
 1        유럽연합 EUR  1511.64  1541.72  1481.56  1526.75  1496.53  1.039
 2   일본 JPY (100엔)   943.33   959.83   926.83   952.57   934.09  0.648
 3          중국 CNY   199.46   209.43   189.49   201.45   197.47  0.137
 4          홍콩 HKD   186.73   190.40   183.06   188.59   184.87  0.128
 5          대만 TWD    44.16    49.94    39.75      NaN      NaN  0.030
 6          영국 GBP  1807.64  1843.25  1772.03  1825.71  1789.57  1.242
 7          오만 OMR  3778.96  4043.48  3514.44      NaN      NaN  2.597
 8         캐나다 CAD  1004.97  1024.76   985.18  1015.01   994.93  0.691
 9         스위스 CHF  1599.23  1630.73  1567.73  1615.22  1583.24  1.099
 10        스웨덴 SEK   131.68   136.02   124.18   132.99   130.37  0.091
 11         호주 AUD   905.38   923.21   887.55   914.43   896.33  0.622
 12       뉴질랜드 NZD   821.00   837.17   804.83   829.21   812.79  0.564
 13         체코 CZK    60.17    65.28    54.76    60.83    59.51  0.041
 14         칠레 CLP     1.48     1.62     1.34      NaN      NaN  0.001
 15       튀르키예 TRY    40.57      NaN      NaN    41.01    40.13  0.028
 16         몽골 MNT     0.42      NaN      NaN      NaN      NaN  0.000
 17       이스라엘 ILS   405.98   446.57   373.51      NaN      NaN  0.279
 18        덴마크 DKK   202.58   209.26   191.04   204.60   200.56  0.139
 19       노르웨이 NOK   128.57   132.81   121.25   129.85   127.29  0.088
 20    사우디아라비아 SAR   387.85   412.28   361.09   391.72   383.98  0.267
 21       쿠웨이트 KWD  4716.05  5022.59  4338.77  4763.21  4668.89  3.242
 22        바레인 BHD  3859.25  4106.24  3550.51  3897.84  3820.66  2.653
 23     아랍에미리트 AED   396.12   417.90   368.79   400.08   392.16  0.272
 24        요르단 JOD  2050.60  2233.10  1886.56      NaN      NaN  1.409
 25        이집트 EGP    28.96      NaN      NaN      NaN      NaN  0.020
 26         태국 THB    43.27    45.43    40.68    43.70    42.84  0.030
 27       싱가포르 SGD  1074.48  1095.86  1053.10  1085.22  1063.74  0.739
 28      말레이시아 MYR   329.42   353.79   305.05      NaN   326.13  0.226
 29  인도네시아 IDR 100     8.94     9.83     8.05     9.02     8.86  0.006
 30        카타르 QAR   399.06      NaN      NaN      NaN      NaN  0.274
 31      카자흐스탄 KZT     2.80      NaN      NaN      NaN      NaN  0.002
 32       브루나이 BND  1074.48  1117.45  1010.02      NaN      NaN  0.739
 33         인도 INR    16.79      NaN      NaN    16.98    16.60  0.012
 34       파키스탄 PKR     5.22      NaN      NaN      NaN      NaN  0.004
 35      방글라데시 BDT    11.93      NaN      NaN      NaN      NaN  0.008
 36        필리핀 PHP    24.94    27.43    22.90    25.18    24.70  0.017
 37        멕시코 MXN    70.38    77.76    63.00    71.08    69.68  0.048
 38        브라질 BRL   247.63   272.88   222.87      NaN   244.66  0.170
 39    베트남 VND 100     5.87     6.56     5.18     5.92     5.82  0.004
 40  남아프리카 공화국 ZAR    78.44    84.71    72.17    79.38    77.50  0.054
 41        러시아 RUB    14.62    16.00    12.07    15.13    14.11  0.010
 42        헝가리 HUF     3.70     4.04     3.41     3.74     3.66  0.003
 43        폴란드 PLN   359.47   388.22   330.72   363.42   355.52  0.247
 44       스리랑카 LKR     4.89      NaN      NaN      NaN      NaN  0.003
 45        알제리 DZD    10.78      NaN      NaN      NaN      NaN  0.007
 46         케냐 KES    11.27      NaN      NaN      NaN      NaN  0.008
 47       콜롬비아 COP     0.35      NaN      NaN      NaN      NaN  0.000
 48       탄자니아 TZS     0.57      NaN      NaN      NaN      NaN  0.000
 49         네팔 NPR    10.50      NaN      NaN      NaN      NaN  0.007
 50       루마니아 RON   303.78      NaN      NaN   307.12   300.44  0.209
 51        리비아 LYD   296.33      NaN      NaN   299.29   293.37  0.204
 52        마카오 MOP   181.16      NaN      NaN      NaN      NaN  0.125
 53        미얀마 MMK     0.69      NaN      NaN      NaN      NaN  0.001
 54      에티오피아 ETB    11.53      NaN      NaN      NaN      NaN  0.008
 55     우즈베키스탄 UZS     0.11      NaN      NaN      NaN      NaN  0.000
 56       캄보디아 KHR     0.36      NaN      NaN      NaN      NaN  0.000
 57         피지 FJD   620.81      NaN      NaN      NaN      NaN  0.427]

In [9]:
url='https://finance.naver.com/marketindex/exchangeDailyQuote.naver?marketindexCd=FX_USDKRW&page=1'

dfs=pd.read_html(url,encoding='cp949',header=1)
dfs

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

[           날짜   매매기준율  전일대비     사실 때     파실 때   보내실 때   받으실 때
 0  2025.01.31  1455.1   9.1  1480.56  1429.64  1469.3  1440.9
 1  2025.01.24  1446.0   9.5  1471.30  1420.70  1460.1  1431.9
 2  2025.01.23  1436.5   0.5  1461.63  1411.37  1450.5  1422.5
 3  2025.01.22  1437.0   0.5  1462.14  1411.86  1451.0  1423.0
 4  2025.01.21  1436.5   4.5  1461.63  1411.37  1450.5  1422.5
 5  2025.01.20  1441.0  18.5  1466.21  1415.79  1455.1  1426.9
 6  2025.01.17  1459.5   2.0  1485.04  1433.96  1473.8  1445.2
 7  2025.01.16  1457.5   1.5  1483.00  1432.00  1471.7  1443.3
 8  2025.01.15  1456.0   5.0  1481.48  1430.52  1470.2  1441.8
 9  2025.01.14  1461.0   7.0  1486.56  1435.44  1475.3  1446.7]

In [10]:
# 페이지 번호 달라지게끔

base_url='https://finance.naver.com/marketindex/exchangeDailyQuote.naver?marketindexCd=FX_USDKRW&page='

df=pd.DataFrame()
for page_num in range(1,3):
    url=base_url+str(page_num)
    dfs=pd.read_html(url,encoding='cp949',header=1)
    print(dfs)

[           날짜   매매기준율  전일대비     사실 때     파실 때   보내실 때   받으실 때
0  2025.01.31  1455.3   9.3  1480.76  1429.84  1469.5  1441.1
1  2025.01.24  1446.0   9.5  1471.30  1420.70  1460.1  1431.9
2  2025.01.23  1436.5   0.5  1461.63  1411.37  1450.5  1422.5
3  2025.01.22  1437.0   0.5  1462.14  1411.86  1451.0  1423.0
4  2025.01.21  1436.5   4.5  1461.63  1411.37  1450.5  1422.5
5  2025.01.20  1441.0  18.5  1466.21  1415.79  1455.1  1426.9
6  2025.01.17  1459.5   2.0  1485.04  1433.96  1473.8  1445.2
7  2025.01.16  1457.5   1.5  1483.00  1432.00  1471.7  1443.3
8  2025.01.15  1456.0   5.0  1481.48  1430.52  1470.2  1441.8
9  2025.01.14  1461.0   7.0  1486.56  1435.44  1475.3  1446.7]
[           날짜   매매기준율  전일대비     사실 때     파실 때   보내실 때   받으실 때
0  2025.01.13  1468.0   6.8  1493.69  1442.31  1482.3  1453.7
1  2025.01.10  1474.8  14.1  1500.60  1449.00  1489.2  1460.4
2  2025.01.09  1460.7   0.3  1486.26  1435.14  1475.0  1446.4
3  2025.01.08  1461.0   6.5  1486.56  1435.44  1475.3  1446.7
4  2025.01.07  1454.5   8.4  1479.95  1429.05  1468.7  1440.3
5  2025.01.06  1462.9   8.1  1488.50  1437.30  1477.2  1448.6
6  2025.01.03  1471.0   0.5  1496.74  1445.26  1485.4  1456.6
7  2025.01.02  1471.5   5.5  1497.25  1445.75  1485.9  1457.1
8  2024.12.31  1477.0   5.2  1502.84  1451.16  1491.4  1462.6
9  2024.12.30  1471.8   4.2  1497.55  1446.05  1486.2  1457.4]

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

In [16]:
# 페이지 번호 달라지게끔

base_url='https://finance.naver.com/marketindex/exchangeDailyQuote.naver?marketindexCd=FX_USDKRW&page='

df=pd.DataFrame()
for page_num in range(1,5):
    url=base_url+str(page_num)
    dfs=pd.read_html(url,encoding='cp949',header=1)
    df=pd.concat([df,dfs[0]]) # dfs는 리스트임!
df

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

           날짜   매매기준율  전일대비     사실 때     파실 때   보내실 때   받으실 때
0  2025.01.31  1455.2   9.2  1480.66  1429.74  1469.4  1441.0
1  2025.01.24  1446.0   9.5  1471.30  1420.70  1460.1  1431.9
2  2025.01.23  1436.5   0.5  1461.63  1411.37  1450.5  1422.5
3  2025.01.22  1437.0   0.5  1462.14  1411.86  1451.0  1423.0
4  2025.01.21  1436.5   4.5  1461.63  1411.37  1450.5  1422.5
5  2025.01.20  1441.0  18.5  1466.21  1415.79  1455.1  1426.9
6  2025.01.17  1459.5   2.0  1485.04  1433.96  1473.8  1445.2
7  2025.01.16  1457.5   1.5  1483.00  1432.00  1471.7  1443.3
8  2025.01.15  1456.0   5.0  1481.48  1430.52  1470.2  1441.8
9  2025.01.14  1461.0   7.0  1486.56  1435.44  1475.3  1446.7
0  2025.01.13  1468.0   6.8  1493.69  1442.31  1482.3  1453.7
1  2025.01.10  1474.8  14.1  1500.60  1449.00  1489.2  1460.4
2  2025.01.09  1460.7   0.3  1486.26  1435.14  1475.0  1446.4
3  2025.01.08  1461.0   6.5  1486.56  1435.44  1475.3  1446.7
4  2025.01.07  1454.5   8.4  1479.95  1429.05  1468.7  1440.3
5  2025.01.06  1462.9   8.1  1488.50  1437.30  1477.2  1448.6
6  2025.01.03  1471.0   0.5  1496.74  1445.26  1485.4  1456.6
7  2025.01.02  1471.5   5.5  1497.25  1445.75  1485.9  1457.1
8  2024.12.31  1477.0   5.2  1502.84  1451.16  1491.4  1462.6
9  2024.12.30  1471.8   4.2  1497.55  1446.05  1486.2  1457.4
0  2024.12.27  1476.0   6.8  1501.83  1450.17  1490.4  1461.6
1  2024.12.26  1469.2  10.0  1494.91  1443.49  1483.5  1454.9
2  2024.12.24  1459.2   6.6  1484.73  1433.67  1473.5  1444.9
3  2024.12.23  1452.6   3.1  1478.02  1427.18  1466.8  1438.4
4  2024.12.20  1449.5   1.5  1474.86  1424.14  1463.7  1435.3
5  2024.12.19  1448.0   3.7  1473.34  1422.66  1462.1  1433.9
6  2024.12.18  1451.7  13.5  1477.10  1426.30  1465.9  1437.5
7  2024.12.17  1438.2   0.3  1463.36  1413.04  1452.2  1424.2
8  2024.12.16  1438.5   2.3  1463.67  1413.33  1452.5  1424.5
9  2024.12.13  1436.2   4.4  1461.33  1411.07  1450.2  1422.2
0  2024.12.12  1431.8   1.3  1456.85  1406.75  1445.8  1417.8
1  2024.12.11  1430.5   5.0  1455.53  1405.47  1444.5  1416.5
2  2024.12.10  1435.5   3.5  1460.62  1410.38  1449.5  1421.5
3  2024.12.09  1432.0   8.0  1457.06  1406.94  1446.0  1418.0
4  2024.12.06  1424.0   7.5  1448.92  1399.08  1437.9  1410.1
5  2024.12.05  1416.5   3.0  1441.28  1391.72  1430.3  1402.7
6  2024.12.04  1413.5   4.0  1438.23  1388.77  1427.3  1399.7
7  2024.12.03  1417.5  11.0  1442.30  1392.70  1431.3  1403.7
8  2024.12.02  1406.5  10.0  1431.11  1381.89  1420.2  1392.8
9  2024.11.29  1396.5   0.0  1420.93  1372.07  1410.1  1382.9